# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "dev", "qa", "prod" ]
  pull_request:
    branches: [ "dev", "qa", "prod" ]

env:
  PORT: ${{secrets.PORT}}
  DB_HOST: ${{secrets.DB_HOST}}
  DB_USER: ${{secrets.DB_USER}}
  DB_PASSWORD: ${{secrets.DB_PASSWORD}}
  DB_DATABASE: ${{secrets.DB_DATABASE}}
  DB_PORT: ${{secrets.DB_PORT}}

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v -cover ./internal/storage/...
